import { useEffect, useState } from 'react'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { listRecords, removeRecord, saveRecord } from '../services/database'

const blankFor = fields => Object.fromEntries(fields.map(([name]) => [name, '']))
const readableError = error => /row-level security policy for table "estoque"/i.test(error.message)
  ? 'O Supabase bloqueou a criação do saldo inicial deste produto. Execute o arquivo supabase/20260718_corrigir_rls_estoque.sql no SQL Editor.'
  : error.message
export default function CrudPage({ title, table, fields, readOnly = false }) {
  const [rows, setRows] = useState([]); const [references, setReferences] = useState({}); const [form, setForm] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  const referenceTables = [...new Set(fields.filter(([, , type]) => type === 'select').map(([, , , reference]) => reference))]
  const load = () => { setLoading(true); Promise.all([listRecords(table, { orderBy: 'id', ascending: false }), ...referenceTables.map(reference => listRecords(reference, { orderBy: 'nome' }))]).then(([mainRows, ...referenceRows]) => { setRows(mainRows); setReferences(Object.fromEntries(referenceTables.map((reference, index) => [reference, referenceRows[index]]))) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(load, [table])
  const submit = async e => { e.preventDefault(); setError(''); try { await saveRecord(table, form); setForm(null); load() } catch (err) { setError(readableError(err)) } }
  const destroy = async id => { if (!confirm('Excluir este registro?')) return; try { await removeRecord(table, id); load() } catch (err) { setError(readableError(err)) } }
  return <section><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-slate-600">Gerencie os registros cadastrados.</p></div>{!readOnly && <button onClick={() => setForm(blankFor(fields))} className="flex items-center gap-2 rounded-lg bg-brand-500 px-4 py-2.5 font-medium text-white"><Plus size={18}/>Novo</button>}</div>
    {error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}
    {form && <form onSubmit={submit} className="mt-6 grid gap-4 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:grid-cols-2">{fields.map(([name, label, type = 'text', reference]) => <label key={name} className="grid gap-1 text-sm font-medium">{label}{type === 'select' ? <select required value={form[name] ?? ''} onChange={e => setForm({ ...form, [name]: e.target.value === '' ? '' : Number(e.target.value) })} className="rounded-lg border border-slate-300 px-3 py-2 outline-brand-500"><option value="">Selecione</option>{(references[reference] ?? []).map(option => <option key={option.id} value={option.id}>{option.nome}</option>)}</select> : <input required={name === 'nome'} type={type} min={type === 'number' ? '0' : undefined} step={name === 'preco' ? '0.01' : undefined} value={form[name] ?? ''} onChange={e => setForm({ ...form, [name]: type === 'number' && e.target.value !== '' ? Number(e.target.value) : e.target.value })} className="rounded-lg border border-slate-300 px-3 py-2 outline-brand-500" />}</label>)}<div className="flex gap-2 sm:col-span-2"><button className="rounded-lg bg-brand-500 px-4 py-2 text-white">Salvar</button><button type="button" onClick={() => setForm(null)} className="rounded-lg px-4 py-2 text-slate-600">Cancelar</button></div></form>}
    <div className="mt-6 overflow-x-auto rounded-xl bg-white shadow-sm ring-1 ring-slate-200"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{fields.map(([, label]) => <th key={label} className="p-4 font-medium">{label}</th>)}{!readOnly && <th className="p-4">Ações</th>}</tr></thead><tbody>{loading ? <tr><td className="p-4" colSpan={fields.length + 1}>Carregando...</td></tr> : rows.length ? rows.map(row => <tr key={row.id} className="border-t border-slate-100">{fields.map(([name]) => <td key={name} className="p-4">{row[name] ?? '—'}</td>)}{!readOnly && <td className="p-4"><button onClick={() => setForm(row)} className="mr-3 text-brand-500"><Pencil size={17}/></button><button onClick={() => destroy(row.id)} className="text-red-600"><Trash2 size={17}/></button></td>}</tr>) : <tr><td className="p-4 text-slate-500" colSpan={fields.length + 1}>Nenhum registro encontrado.</td></tr>}</tbody></table></div>
  </section>
}
