import { useEffect, useMemo, useState } from 'react'
import { listRecords } from '../services/database'
import { requireSupabase } from '../services/supabase'

export default function SalesPage() {
  const [data, setData] = useState({ clientes: [], vendedores: [], produtos: [] }); const [client, setClient] = useState(''); const [seller, setSeller] = useState(''); const [items, setItems] = useState([]); const [product, setProduct] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState('')
  useEffect(() => { Promise.all(['clientes', 'vendedores', 'produtos'].map(listRecords)).then(([clientes, vendedores, produtos]) => setData({ clientes, vendedores, produtos })).catch(e => setError(e.message)) }, [])
  const total = useMemo(() => items.reduce((sum, item) => sum + item.quantidade * Number(item.preco), 0), [items])
  const addItem = () => { const selected = data.produtos.find(p => String(p.id) === product); if (!selected) return; setItems([...items, { ...selected, quantidade: 1 }]); setProduct('') }
  const save = async () => { try { setError(''); const api = requireSupabase(); const { data: sale, error: saleError } = await api.from('vendas').insert({ cliente_id: client || null, vendedor_id: seller || null, valor_total: total }).select().single(); if (saleError) throw saleError; const { error: itemError } = await api.from('venda_itens').insert(items.map(i => ({ venda_id: sale.id, produto_id: i.id, quantidade: i.quantidade, valor_unitario: i.preco, subtotal: i.quantidade * i.preco }))); if (itemError) throw itemError; setItems([]); setClient(''); setSeller(''); setDone('Venda registrada com sucesso.') } catch (e) { setError(e.message) } }
  return <section><h1 className="text-2xl font-bold">Nova venda</h1><p className="mt-1 text-slate-600">Adicione os itens e confirme o pedido.</p>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{done && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-emerald-700">{done}</p>}
    <div className="mt-6 grid gap-4 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200 md:grid-cols-2"><Select label="Cliente" value={client} onChange={setClient} options={data.clientes}/><Select label="Vendedor" value={seller} onChange={setSeller} options={data.vendedores}/><div className="md:col-span-2"><Select label="Produto" value={product} onChange={setProduct} options={data.produtos}/><button onClick={addItem} className="mt-2 rounded-lg border border-brand-500 px-3 py-2 text-brand-500">Adicionar item</button></div></div>
    <div className="mt-6 rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200">{items.map((item, index) => <div key={`${item.id}-${index}`} className="flex items-center justify-between border-b py-3"><span>{item.nome}</span><input type="number" min="1" value={item.quantidade} onChange={e => setItems(items.map((x, i) => i === index ? { ...x, quantidade: Number(e.target.value) } : x))} className="w-16 rounded border p-1"/><span>R$ {(item.quantidade * item.preco).toFixed(2)}</span></div>)}<div className="mt-4 flex items-center justify-between text-lg font-bold"><span>Total</span><span>R$ {total.toFixed(2)}</span></div><button disabled={!items.length} onClick={save} className="mt-5 rounded-lg bg-brand-500 px-4 py-2.5 font-medium text-white disabled:opacity-50">Finalizar venda</button></div>
  </section>
}
function Select({ label, value, onChange, options }) { return <label className="grid gap-1 text-sm font-medium">{label}<select value={value} onChange={e => onChange(e.target.value)} className="rounded-lg border border-slate-300 px-3 py-2"><option value="">Selecione</option>{options.map(option => <option key={option.id} value={option.id}>{option.nome}</option>)}</select></label> }
